version: '2'

services:

  php:
    build: ./php
    links:
      - mysql:mysql
    volumes:
      - "./src:/var/www/html:rw"

  nginx:
    image: nginx:alpine
    links:
      - php:php
    ports:
      - "80"
    volumes:
      - "./src:/var/www/html:rw"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  mysql:
    image: mysql:5
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306"


